version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Building TypeScript project...
      - npm run build
      - npm test
  post_build:
    commands:
      - echo Packaging Lambda...
      - mkdir -p artifact
      - cp -r dist/* node_modules package.json artifact/
      - cd artifact
      - zip -r function.zip * > /dev/null 2>&1
      - echo Uploading to S3...
      - aws s3 cp function.zip s3://playlist-transfer-artifact-bucket/function.zip

artifacts:
  files:
    - artifact/function.zip
