app: playlistTransferBackend
service: playlist-transfer-backend

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 15
  memorySize: 512
  region: eu-west-2

package:
  individually: true

functions:
  app:
    handler: dist/serverless.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: '/{proxy+}'
          method: ANY
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 5001
    noPrependStageInUrl: true
